name: Code Scanning

on:
  pull_request:
    types: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@master
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
           
      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           
 

      - name: Check SonarQube results
        run: |
          apt-get update && apt-get install -y jq
  
          if jq -e '.[] | select(.bugs > 0 or .vulnerabilities > 0)' < path/to/sonarqube-report.json; then
            echo "SonarQube found issues, blocking PR creation."
            exit 1
          else
            echo "SonarQube scan successful. PR creation allowed."
          fi

     
